routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get ( '/', function () {
//     return view ( 'welcome' );
// } );

Route::get('/', 'WelcomeController@welcome')->name('home');

Route::get('/showcategory/{id}', 'CategoryController@index')->name('category.show');

Route::post('/search', 'SearchController@search')->name('search');
Route::get('/showselected/{id}', 'ProductController@index')->name('showselectedproduct');
Route::get('/cart', 'CartController@index')->name('cart');

Route::post('/cart/{id}/reduce', 'CartController@reduceQuantity')->name('qty.reduce');
Route::post('/cart/{id}/add', 'CartController@addQuantity')->name('qty.add');

Route::post('/order', 'OrderController@createOrder')->name('order');

Route::post('/subscribe', 'SubscribersController@index')->name('subscribers');
Route::post('/create/comment/{id}', 'CommentsController@create')->name('createcomment');

Route::get('/addtocart/{id}', 'CartController@addToCart')->name('addtocart');
Route::get('/deletefromcart/{id}', 'CartController@remove')->name('remove');
Route::get('/emptycart', 'CartController@deletecart')->name('emptycart');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group([
    'middleware' => ['web', 'auth', 'role:admin'],
    'prefix'     => 'admin',
    'as'         => 'admin.',
], function () {

    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('media', 'Admin\MediaController');
    Route::resource('news', 'Admin\NewsController');
    Route::post('product/{id}/activate', ['uses' => 'Admin\ProductController@activate', 'as' => 'product.activate']);

    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('media', 'Admin\MediaController');
    Route::resource('news', 'Admin\NewsController');

    Route::get('/orders', [
        'uses' => 'Admin\OrdersController@index',
        'as'   => 'orders',
    ]);

});

app/Media.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{

    protected $fillable = [
        'title',
        'type',
        'url',

    ];

    public function getImageAttribute($url)
    {
        return asset($url) ?? '';
    }

}

app/Http/Controllers/Admin/MediaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateMediaRequest;
use App\Media;
use Image;

class MediaController extends Controller
{

    public function index()
    {
        $all = Media::all();

        return view('admin.media.index', compact('all'));
    }

    public function create()
    {

        return view("admin.media.create");
    }

    public function store(CreateMediaRequest $request)
    {
        $all = Media::all();
        $url = $request->url;

        $NewFileName = time() . $url->getClientOriginalName();

        $url->move('uploads/product', $NewFileName);
        $store = Media::create([
            'title' => $request->title,
            'type'  => $request->type,
            'url'   => 'uploads/product/' . $NewFileName,

        ]);
        return redirect()->route ('admin.media.index');
    }

    public function show($id)
    {
//        $all = Media::find ( $id );
        //
        //        // return view('media.show', compact('all'));
        //        return redirect ( route ( 'admin.media.index' ) );
    }

    public function edit($id)
    {
        $edit = Media::find($id);
        return view('admin.media.edit', compact('edit'));
    }

    public function update(CreateMediaRequest $request, $id)
    {
        $media = Media::find($id);
        if (request()->hasFile('url')) {

            $url         = $request->url;
            $NewFileName = time() . $url->getClientOriginalName();
            $url->move('uploads/product', $NewFileName);
            $media->url = 'uploads/product/' . $NewFileName;
        }

        $save = $media->fill([
            'title' => $request->title,
            'type'  => $request->type,

        ]

        );
        $save->save();
        return redirect(route('admin.media.index'));
    }

    public function destroy($id)
    {
        $type = Media::find($id);
        $type->delete();

        return redirect(route('admin.media.index'));
    }

}

resources/views/admin/media/_form.blade.php
<div class="form-group row">
   {{Form::label('title', 'Title', ['class' => 'col-sm-2 col-form-label col-form-label-sm'])}}
   <div class="col-sm-8">
   {{ Form::text('title',$edit->title ?? null ,['class' => 'form-control form-control-sm'])}}
  </div>
  @if ($errors->has('title'))
    <div class="alert alert-danger col-sm-2" role="alert">
  {{ $errors->first('title') }}
  </div>
  @endif
</div>
<div class="form-group row">
   {{Form::label('type', 'Type', ['class' => 'col-sm-2 col-form-label col-form-label-sm'])}}
   <div class="col-sm-8">
   <!-- {{ Form::text('type',null ,['class' => 'form-control form-control-sm'])}} -->
   {{Form::select('type', ['music' => 'music', 'video' => 'video','image'=>'image'],NULL, array('class' => 'form-control form-control-sm'))}}
  </div>
   @if ($errors->has('type'))
    <div class="alert alert-danger col-sm-2" role="alert">
  {{ $errors->first('type') }}
   </div>
  @endif
  </div>

<div class="form-group row">

   {{Form::label('url', 'Url', ['class' => 'col-sm-2 col-form-label col-form-label-sm'])}}
   <div class="col-sm-8">
   {{ Form::file('url',['class' => 'form-control form-control-sm'])}}
  </div>
   @if ($errors->has('url'))
    <div class="alert alert-danger col-sm-2" role="alert">
  {{ $errors->first('url') }}
   </div>
  @endif
  </div>
{{ Form::submit('Save',['class' => 'btn btn-primary'])}}

resources/views/admin/media/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="col-lg-9">
		<h1>Creation...</h1>

		<br>
  {!!Form::open(['route' => 'admin.media.store','files' => true],['class' => 'form'])!!}
  {{ csrf_field() }}
	@include('admin.media._form')
{!! Form::close() !!}
    </div>
@endsection

resources/views/admin/media/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="col-lg-9">
<h1>Editing....</h1>
{!!Form::model($edit,['route' => ['admin.media.update', $edit->id],'method' => 'put','files' => true],['class' => 'form'])!!}

@include('admin.media._form')

{!! Form::close() !!}

    </div>
@endsection

resources/views/admin/media/index.blade.php
@extends('adminlte::page')
@section('content')
    <div class="col-lg-9">
        <h2>Media</h2>
        <hr>
        <a href="{{route('admin.media.create')}}" class="btn btn-primary">Create New Type</a>
        <hr>
        <table class="table table-active">
            <tr>
                <th>Image</th>
                <th>ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Url</th>
            </tr>
            @foreach($all as $i)
                <tr>

                    <td><img src="{{asset($i->url)}}" height="72" width="72" alt=""></td>
                    <td>{{$i->id}}</td>
                    <td>{{$i->title}}</td>
                    <td>{{$i->type}}</td>
                    <td>{{$i->url}}</td>
                    <td>
                        <form action="{{route('admin.media.destroy',$i->id)}}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                    <td>
                        <a href="{{route('admin.media.edit',$i->id)}}" class="btn btn-success">edit</a>
                    </td>
                    <td>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
    @endsection