routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get ( '/', function () {
//     return view ( 'welcome' );
// } );

Route::get('/', 'WelcomeController@welcome')->name('home');

Route::get('/showcategory/{id}', 'CategoryController@index')->name('category.show');

Route::post('/search', 'SearchController@search')->name('search');
Route::get('/showselected/{id}', 'ProductController@index')->name('showselectedproduct');
Route::get('/cart', 'CartController@index')->name('cart');

Route::post('/cart/{id}/reduce', 'CartController@reduceQuantity')->name('qty.reduce');
Route::post('/cart/{id}/add', 'CartController@addQuantity')->name('qty.add');

Route::post('/order', 'OrderController@createOrder')->name('order');

Route::post('/subscribe', 'SubscribersController@index')->name('subscribers');
Route::post('/create/comment/{id}', 'CommentsController@create')->name('createcomment');

Route::get('/addtocart/{id}', 'CartController@addToCart')->name('addtocart');
Route::get('/deletefromcart/{id}', 'CartController@remove')->name('remove');
Route::get('/emptycart', 'CartController@deletecart')->name('emptycart');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group([
    'middleware' => ['web', 'auth', 'role:admin'],
    'prefix'     => 'admin',
    'as'         => 'admin.',
], function () {

    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('media', 'Admin\MediaController');
    Route::resource('news', 'Admin\NewsController');
    Route::post('product/{id}/activate', ['uses' => 'Admin\ProductController@activate', 'as' => 'product.activate']);

    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('media', 'Admin\MediaController');
    Route::resource('news', 'Admin\NewsController');

    Route::get('/orders', [
        'uses' => 'Admin\OrdersController@index',
        'as'   => 'orders',
    ]);

});

app/Product.php
<?php

namespace App;

use Gloudemans\Shoppingcart\Contracts\Buyable;
use Illuminate\Database\Eloquent\Model;

class Product extends Model implements Buyable {

	protected $fillable = [
		'title',
		'description',
		'price',
		'category_id',
		'active',
		'image',
	];

	//get full path to image
	public function getImageAttribute ( $image ) {
		return asset ( $image ) ?? '';
	}


	public function getBuyableIdentifier ( $options = null ) {
		return $this->id;
	}

	public function getBuyableDescription ( $options = null ) {
		return $this->name;
	}


	public function getBuyablePrice ( $options = null ) {
		return $this->price;
	}


	public function orders () {
		return $this->hasMany  ( 'App\ProductsOrder' );
	}


	public function category () {
		return $this->belongsTo ( 'App\Category' );
	}

    public function comment()
    {
        return $this->hasMany('App\Comments');
    }

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\ProductFormRequest;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Image;

class ProductController extends Controller
{
    public function index()
    {
        //return view ( 'home' );
        $products = Product::all();

        return view('admin.product.index', compact('products'));
    }

    public function create()
    {
        $category = Category::all();

        return view('admin.product.create', compact("category"));

    }

    public function activate(Request $request, $id)
    {

        $product = Product::findOrFail($id);

        if ($product->active == 1) {
            $product->active = 0;
            $product->save();

            return $product->active;
        } else {
            $product->active = 1;
            $product->save();

            return $product->active;
        }

    }

    public function store(ProductFormRequest $request)
    {
        $image        = $request->image;
        $imageNewName = time() . $image->getClientOriginalName();
        $image->move('uploads/product/', $imageNewName);
        $product = Product::create([
            'title'       => $request->title,
            'description' => $request->description,
            'image'       => 'uploads/product/' . $imageNewName,
            'category_id' => $request->category_id,
            'price'       => $request->price,
        ]);

        Session::flash('Success', 'Пост збережений');
        return redirect()->route('admin.product.index');
    }

    public function show($id)
    {
        $product = Product::find($id);

        return view('admin.product.show', compact('product'));

        return redirect('admin/product');
    }

    public function edit($id)
    {
        $product = Product::findOrFail($id);

        return view('admin.product.edit')->with('product', $product)->with('category', Category::all());
    }

    public function update(ProductFormRequest $request, $id)
    {
        $product = Product::findOrFail($id);
        if ($request->hasFile('image')) {
            $image        = $request->image;
            $imageNewName = time() . $image->getClientOriginalName();
            $image->move('uploads/product', $imageNewName);
            $product->image = 'uploads/product/' . $imageNewName;

        }
        $product->title       = $request->title;
        $product->description = $request->description;
        $product->price       = $request->price;
        $product->category_id = $request->category_id;
        $product->save();
        Session::flash('Success', 'Пост успішно оновлений!');

        return redirect()->route('admin.product.index');

    }

    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        Session::flash('Success', 'Пост успішно видалений!');

        return redirect()->route('admin.product.index');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Comments;
use App\Product;
use App\User;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{
    public function index($id)
    {
        $product = Product::where(['id' => $id, 'active' => 1])->firstOrFail();
        /**
         * [$categories description]
         * $categories needs for nav menu;
         * @var [type]
         */
        $categories = Category::orderBy('sort_order', 'asc')->get();

        /**
         * [$productsSession description]
         * this variable need for know what products were seen by client,first take previous date from session
         * @var [type]
         */
        // session()->forget('some_data');
        // session()->flush();
        $productsSession = session('visited');

        /**
         * [$arraysession description]
         *create array of id products
         * @var [type]
         */
        $arraysession = session()->push('visited', $id);
        /**
         * [$productsSession description]
         * this variable need for know what products were seen by client, take all date from session
         * @var [type]
         */
        $productsSession = session('visited');
        // dd($productsSession);

        /**
         * finding id of selected products
         * @var [type]
         */

        /**
         * finding id of selected category
         */

        $idCategory = $product->category_id;

        /**
         * [$productsOrder description]
         * selecting last products with price asc
         * @var [type]
         */
        // $productsBest = Product::where('category_id', '=', $idCategory)->orderBy('price', 'asc')->paginate(3);
        $productsBest = Product::where('category_id', '=', $idCategory)->where('active', '=', 1)->orderBy('price', 'asc')->paginate(3);

        /**
         * $productsOrderAll ->this is data of visiting products of person
         * @var [type]
         */
        // dd($productsSession);
        // $productsVisited
        // $productsVisited = Product::whereIn('id', $productsSession)->orderBy('price', 'desc')->paginate(6);
        $productsVisited = Product::whereIn('id', $productsSession)->where('active', '=', 1)->orderBy('price', 'desc')->paginate(3);
        $count           = Cart::count();
        $comments        = Comments::all();
        $commentsProduct = Comments::where('product_id', '=', $id)->get();
        $countComments   = count($commentsProduct);
        // dd($commentsProduct[0]->user);

        return view('product.showproduct', compact('categories', 'product', 'productsBest', 'productsVisited', 'count', 'comments', 'commentsProduct', 'countComments'));
    }
}

resources/views/admin/product/create.blade.php
@extends('adminlte::page')
@section('content')
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Створити новий товар</h2>
            </div>
            <div class="panel-body">
                <form action="{{route('admin.product.store')}}" method="post" enctype="multipart/form-data">
                    {{csrf_field ()}}
                    <div class="form-group">
                        <label for="title">Заголовок</label>
                        <input type="text" name="title" class="form-control" value="{{old ('title')}}">
                        @if ($errors->has('title'))
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first('title') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="image">Зображення</label>
                        <input type="file" name="image" class="form-control">
                        @if ($errors->has('image'))
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first('image') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="category">Виберіть категорію</label>
                        <select name="category_id" id="category" class="form-control" name="category">
                            @foreach($category as $cat)
                                <option value="{{$cat->id}}">{{$cat->category_name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="description">Опис</label>
                        <textarea type="text" name="description" class="form-control" id="content" cols="5"
                                  rows="5">{{old ('description')}}</textarea>
                        @if ($errors->has('description'))
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first('description') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="price">Ціна</label>
                        <input type="text" name="price" class="form-control" value="{{old ('price')}}">
                        @if ($errors->has('price'))
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first('price') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <div class="text-center">
                            <button class="btn btn-success">
                                Зберегти
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('adminlte::page')
@section('content')
    <div class="col-lg-9">
    @include('admin.includes.errors')
    <div class="panel panel-default">
        @if(Session::has('Success'))
            <div class="alert alert-success" role="alert">
            </div>
        @endif
        <div class="panel-heading">
            Редагувати пост:<strong>{{$product->title}}</strong>
        </div>
        <div class="panel-body">
            <form action="{{route('admin.product.update', ['id'=>$product->id])}}" method="post"
                  enctype="multipart/form-data">
                {{csrf_field ()}}
                {{ method_field('PATCH') }}
                <a href="{{route('admin.product.index')}}" class="btn btn-primary pull-right">Назад</a>
                <div class="form-group">
                    <label for="title">Заголовок</label>
                    <input type="text" name="title" class="form-control" value="{{$product->title}}">
                </div>
                <div class="form-group">
                    <label for="image">Зображення</label>
                    <input type="file" name="image" class="form-control">
                </div>
                <div class="form-group">
                    <label for="category">Виберіть категорію</label>
                    <select name="category_id" id="category" class="form-control">
                        @foreach($category as $cat)
                            <option value="{{$cat->id}}">{{$cat->category_name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="description">Опис</label>
                    <textarea type="text" name="description" class="form-control" id="content" cols="5"
                              rows="5">{{$product->description}}</textarea>
                </div>
                <div class="form-group">
                    <label for="title">Ціна</label>
                    <input type="text" name="price" class="form-control" value="{{$product->price}}">
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success">
                            Оновити
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/product/index.blade.php
@extends('adminlte::page')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <div class="col-lg-9">
        <h2>Products</h2>
        <div class="panel panel-default">
            @if(Session::has('Success'))
                <div class="alert alert-success" role="alert">
                    {{Session::get('Success')}}
                </div>
            @endif
            <div class="panel-body">
                <table class="table table-hover table-responsive text-sm-center" id="table">
                    <a href="{{route('admin.product.create')}}" class="btn btn-primary">Створити продукт</a>
                    <tr class="text-align-center">
                        <thead>
                        <th>
                            Зображення
                        </th>
                        <th>
                            Назва
                        </th>
                        <th>
                            Опис
                        </th>
                        <th>
                            Ціна
                        </th>
                        <th>
                            Активувати
                        </th>
                        <th>
                            Створено
                        </th>
                        <th>
                            Ред
                        </th>
                        <th>
                            Видал
                        </th>
                        </thead>

                    </tr>
                    <tbody>
                    @foreach($products as $p)
                        <tr>
                            <td><a href="{{route ('admin.product.show', ['id'=>$p->id])}}">
                                    <img src="{{$p->image}}" height="72" width="72"></a></td>
                            <td>{{$p->title}}</td>
                            <td>{{$p->description}}</td>
                            <td>{{$p->price}}</td>
                            <td>
                                <input data-action="{{route('admin.product.activate', ['id'=>$p->id])}}" type="checkbox"
                                       name="activatebtn" value="{{$p->id}}"
                                        {{($p->active==1)?'checked="checked"' : ''}}>
                            </td>
                            <td>{{$p->created_at->diffForHumans()}}</td>
                            <td><a href="{{route('admin.product.edit', ['id'=>$p->id])}}" class="btn btn-info btn-xs">Редагувати</a>
                            </td>
                            <td>
                                <form action="{{route('admin.product.destroy', ['id'=>$p->id])}}" method="POST">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button type="submit" class="btn btn-danger btn-xs">X
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            checkbox = $('input[name="activatebtn"]');
            checkbox.change(function () {
                var url = $(this).data('action');
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: 'POST',
                    url: url,
                    contentType: 'json',
                    cache: false,
                    processData: false,
                    success: function (data) {
                        console.log(data);
                    }
                })
            })
        });
    </script>
@stop

resources/views/admin/product/show.blade.php
@extends('adminlte::page')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <div class="col-lg-9">
        <div class="panel panel-default">
        <div class="panel-heading">
            <a href="{{route('admin.product.index')}}" class="btn btn-primary pull-right">Назад</a>
            <h2>{{$product->title}}</h2>
        </div>
        <div class="panel-body">
            <img src="{{$product->image}}" height="auto" width="240">
            <div class="panel-item pull-right col-lg-6">
                <p>Назва:{{$product->title}}</p>
                <p>Опис:{{$product->description}}</p>
                <p>Ціна:{{$product->price}}</p>
                <p>Створено:{{$product->created_at->diffForHumans()}}</p>
            </div>
            </div>
        </div>
        </div>
@endsection