routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get ( '/', function () {
//     return view ( 'welcome' );
// } );

Route::get('/', 'WelcomeController@welcome')->name('home');

Route::get('/showcategory/{id}', 'CategoryController@index')->name('category.show');

Route::post('/search', 'SearchController@search')->name('search');
Route::get('/showselected/{id}', 'ProductController@index')->name('showselectedproduct');
Route::get('/cart', 'CartController@index')->name('cart');

Route::post('/cart/{id}/reduce', 'CartController@reduceQuantity')->name('qty.reduce');
Route::post('/cart/{id}/add', 'CartController@addQuantity')->name('qty.add');

Route::post('/order', 'OrderController@createOrder')->name('order');

Route::post('/subscribe', 'SubscribersController@index')->name('subscribers');
Route::post('/create/comment/{id}', 'CommentsController@create')->name('createcomment');

Route::get('/addtocart/{id}', 'CartController@addToCart')->name('addtocart');
Route::get('/deletefromcart/{id}', 'CartController@remove')->name('remove');
Route::get('/emptycart', 'CartController@deletecart')->name('emptycart');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group([
    'middleware' => ['web', 'auth', 'role:admin'],
    'prefix'     => 'admin',
    'as'         => 'admin.',
], function () {

    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('media', 'Admin\MediaController');
    Route::resource('news', 'Admin\NewsController');
    Route::post('product/{id}/activate', ['uses' => 'Admin\ProductController@activate', 'as' => 'product.activate']);

    Route::resource('product', 'Admin\ProductController');
    Route::resource('category', 'Admin\CategoryController');
    Route::resource('media', 'Admin\MediaController');
    Route::resource('news', 'Admin\NewsController');

    Route::get('/orders', [
        'uses' => 'Admin\OrdersController@index',
        'as'   => 'orders',
    ]);

});

app/Media.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Media extends Model
{

    protected $fillable = [
        'title',
        'type',
        'url',

    ];

    public function getImageAttribute($url)
    {
        return asset($url) ?? '';
    }

}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model {
	protected $table = 'orders';
	protected $fillable = [
		'user_id'
	];

	public function users () {
		return $this->belongsToMany ()    ( 'App\User');
	}

	public function products () {
		return $this->belongsToMany    ( 'App\Product' ,'products_order');
	}

}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductFormRequest;
use Illuminate\Support\Facades\Session;
use App\Product;
use App\ProductsOrder;
use App\User;
use App\Order;

class OrdersController extends Controller {
	public function index () {

//		$userData = [
//			'name'     => 'user123',
//			'email'    => 'mail@mail.com',
//			'password' => bcrypt ( '1' ),
//		];
//
//		//$orders = $user->orders;
//
//		$products = [
//			'title'       => 'Product1',
//			'quantity'    => '3',
//			'image'       => '',
//			'category_id' => 2,
//			'description' => 'lorem',
//			'price'       => '452',
//		];
//$u = new User();
//var_dump(get_class_methods ($u));

		//$user_id = auth ()->user ()->id;
		//$user    = User::find ( 1);
		//$order = Order::all ();
		$o = Order::find (1);
		$orders=$o->products()->get();
		//$u = User::find (1);
		//$users=$u->orders ()->get();
		$p = Product::find (1);
		$products=$p->orders ()->get();
		//dd ($orders_products);

		//$p = Product::all ();
		//dd ($p);
		//$orders = $p;
		//var_dump ( get_class_methods ( $p ) );
		//print_r ( ​get_class_methods ( 'Order' ) );
//
//		}
		return view ( 'admin.orders.index')
                                        ->with('orders', $orders)
//		                                  ->with ('users',$users)
		                                  ->with ('products',$products);
		//return redirect ()->route ( 'admin.orders' );
		//return view ( 'admin.orders.index', compact ( 'products', 'userData' ) );
		//$order->user()->attach();
	}
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRegistrationUserRequest;
use App\Order;
use App\Product;
use App\ProductsOrder;
use App\User;
use Gloudemans\Shoppingcart\Facades\Cart;
// use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;

class OrderController extends Controller
{

    public function createOrder(CreateRegistrationUserRequest $request)
    // public function createOrder(Request $request)
    {

        if (Auth::check()) {
            $id = Auth::id();

        } else {
            $userEmail = $request->email;

            $user = User::where('email', '=', $userEmail)->first();

            if ($user === null) {
                $newUser = User::create([
                    'name'     => $request->name,
                    'email'    => $request->email,
                    'password' => bcrypt(1111),

                ]);

                $id = $newUser->id;

            } else {
                $user == $user;
                $id = $user->id;

            }

        }

        $cartcontent = Cart::content();
        $total       = Cart::subtotal();
        $count       = Cart::count();

        $orderCreate = Order::create([
            'user_id' => $id,

        ]);
        $userId = $orderCreate->id;

        foreach ($cartcontent as $item) {

            $productOrder = ProductsOrder::create([
                'order_id'   => $userId,
                'product_id' => $item->id,
                'quantity'   => $item->qty,

            ]);

        }
        return view('successpage.index', compact('count', 'total', 'cartcontent'));

    }
}

resources/views/admin/orders/detail.order.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 03.12.2017
 * Time: 17:35
 */

resources/views/admin/orders/index.blade.php
@extends('adminlte::page')
@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <div class="col-lg-9">
        <h2>Orders</h2>
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-hover table-responsive table-bproducted text-sm-center" id="table">
                    <tr class="text-align-center">
                        <thead class="bg-primary">
                        <th>
                            №
                        </th>
                        <th>
                            ПІБ покупця
                        </th>
                        <th>
                            Сума, грн
                        </th>
                        <th>
                            Дата замов-ння
                        </th>
                        <th>
                            Статус
                        </th>
                        <th>
                            Mенеджер
                        </th>
                        <th>
                            Управління замовленням
                        </th>
                        </thead>
                    </tr>
                    <tbody>
                    @foreach($orders as $order)
                        <tr>
                            <td>{{$order->id}}</td>
                            @endforeach
                            <td></td>
                            {{--@endforeach--}}
                            {{--@foreach($products as $product)--}}
                            @foreach($products as $product)
                                <td><p>{{$product->title}}</p>
                                    <p><a href="{{route ('admin.product.show', ['id'=>$product->id])}}">
                                            <img src="{{$product->image}}" height="72" width="72"></a>
                                    <p></td>
                                <td>{{$product->price}}</td>
                                <td>Кількість, шт</td>
                                <td>{{$product->created_at->diffForHumans()}}</td>
                                <td>Pending...</td>
                                <td>ПІБ МЕНЕДЖЕРА</td>
                                <td><a href="{{route('admin.product.edit', ['id'=>$product->id])}}"
                                       class="btn btn-info btn-xs">Показати</a>
                                </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/orders/manage_order.blade.php
@extends('adminlte::page')
@section('content')
    <div class="col-lg-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>Оформлення замовлення</h2>
            </div>
            <div class="panel-body">
                <form action="{{route('admin.orders.store')}}" method="post" >
                    {{csrf_field ()}}
                    <div class="form-group">
                        <label for="title">ПІБ менеджера</label>
                        <input type="text" name="manager_name" class="form-control" value="{{old ('title')}}">
                        @if ($errors->has('title'))
                            <div class="alert alert-danger" role="alert">
                                {{ $errors->first('title') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <div class="text-center">
                            <button class="btn btn-success">
                                Зберегти
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/orders/order.status.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 03.12.2017
 * Time: 17:35
 */